version: 2.1

jobs:
  test:
    machine:  # linux environment
      image: ubuntu-2204:2023.07.2
    steps:
      - checkout
      - run: python3 -m pip install -r requirements.txt
      - run: python3 -m pytest

workflows:
  test:
    jobs:
      - test
