version: 2.1

jobs:
  test:
    docker:
      - image: riazzor/oc_lettings:0.1
    steps:
      - checkout
      - run:
          name: Python test
          command: |
            python3 -m pytest
  build:
    docker:
      - image: riazzor/oc_lettings:0.1
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24
          # docker_layer_caching: true
      - run:
          name: Run migrations
          command: |
            python manage.py migrate

      - run:
          name: Run tests
          command: |
            python -m pytest

workflows:
  test-and-build:
    jobs:
      - test
      - build:
          requires:
            - test
      # - deploy:
      #     requires:
      #       - test
      #       - build
      #     filters:
      #       branches:
      #         only: master
