version: 2.1

jobs:
  test:
    docker:
      - image: riazzor/oc_lettings:0.1
    steps:
      - checkout
      - run:
          name: Check linting
          command: |
            flake8
      - run:
          name: Python test and coverage
          command: |
            python3 -m pytest --cov . --cov-fail-under=80

  build:
    docker:
      - image: riazzor/oc_lettings:0.1
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24
      - run:
          name: Run migrations
          command: |
            python manage.py migrate

      - run:
          name: Install docker
          command: |
            apt-get update && apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin
      - run:
          name: Build docker image
          command: |
            docker build -t oc_lettings:$TAG

workflows:
  test-and-build:
    jobs:
      - test
      - build:
          requires:
            - test
      # - deploy:
      #     requires:
      #       - test
      #       - build
      #     filters:
      #       branches:
      #         only: master
